chore: try a few things on PR

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -13,12 +13,19 @@ jobs:
           sudo apt install gcc-aarch64-linux-gnu device-tree-compiler gcc-arm-none-eabi
       - name: Build
         id: build
+        # "shell: bash" implies "-o pipefail" -> pipeliness fail if any part fails
+        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
+        shell: bash
         run: |
           # Store all output so we can publish build log too for
           # later inspection if needed. It's good for transparency too.
           set -e
           mkdir -p build
           ./uboot-builder.sh 2>&1 | tee build/build.log
+          echo ${PIPESTATUS[@]}
+          echo $0
+          echo $SHELL
+          ps -p $$
       - name: Archive artifacts
         # Archive what ever we have even after failed build
         if: ${{ always() }}
